In [2]:
print('Hello World')

Hello World


In [7]:
a='Hello World'
a

'Hello World'

In [6]:
type(a)

str

In [12]:
a[0:8:2]

'HloW'

In [14]:
b=a+" Fin2"
b

'Hello World Fin2'

In [15]:
b.upper()

'HELLO WORLD FIN2'

In [16]:
b.replace("World","Sweetie")

'Hello Sweetie Fin2'

In [20]:
#Escape Squence: \n : new line
#Escape Squence: \t : tab
print('Hello World \d Fin2 Luv')

Hello World \d Fin2 Luv


In [21]:
1+2*3-(6-3)

4

In [22]:
x=2+3
y=5*6
z=x+y
z

35

In [27]:
25%6

1

In [33]:
L=["chocolate","vanilla","matcha","chocolate"]
L
#type(L)

['chocolate', 'vanilla', 'matcha', 'chocolate']

In [34]:
T=("chocolate","vanilla","matcha","chocolate")
T
#type(T)

('chocolate', 'vanilla', 'matcha', 'chocolate')

In [32]:
S={"chocolate","vanilla","matcha","chocolate"}
S

{'chocolate', 'matcha', 'vanilla'}

In [36]:
L=["chocolate","vanilla","matcha","chocolate"]
L.extend(["mint choco","durian"])


In [37]:
L

['chocolate', 'vanilla', 'matcha', 'chocolate', 'mint choco', 'durian']

In [38]:
L.remove('durian')
L

['chocolate', 'vanilla', 'matcha', 'chocolate', 'mint choco']

In [39]:
L.append(["mint choco","durian"])
L

['chocolate',
 'vanilla',
 'matcha',
 'chocolate',
 'mint choco',
 ['mint choco', 'durian']]

In [40]:
L+["strawberry"]

['chocolate',
 'vanilla',
 'matcha',
 'chocolate',
 'mint choco',
 ['mint choco', 'durian'],
 'strawberry']

In [44]:
L

['chocolate',
 'vanilla',
 'matcha',
 'chocolate',
 'mint choco',
 ['mint choco', 'durian']]

In [48]:
L[0:4:2]

['chocolate', 'matcha']

In [50]:
5!=6

True

In [54]:
5!=6 and not(7>8)

True

In [58]:
a="vanilla"
b="chocolate"
c="vanilla ice cream"
"durian" not in c

True

In [65]:
age=19
uni="FTX"
uniset={"FTU","UEH","RMIT"}
if age >=18 and uni in uniset:
    print("You will have a candy")
elif age >=16:
    print("You will have a cake")
elif age >=14:
    print("You will have a muffin")
else:
    print("Sorry, you are not old enough")

You will have a cake


In [67]:
year=1999
if year%4==0:
    print("you were born in a leap year")
else:
    print("you were not born in a leap year")    

you were not born in a leap year


In [1]:
for i in range(-5,6):
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4
5


In [7]:
Genres=['rock','R&B', 'Soundtrack', 'R&B', 'soul', 'pop','ballad']
n=len(Genres)
for i in range(n):
    print(Genres[i])

rock
R&B
Soundtrack
R&B
soul
pop
ballad


In [13]:
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i=0
ratings=PlayListRatings[i]
while ratings >=6:
    print(PlayListRatings[i])
    i=i+1
    ratings=PlayListRatings[i]

10
9.5
10
8
7.5


In [15]:
x=8
print('This is the timetable of ',x)
for i in range(1,11):
    print(x,' x ', i,' = ',x*i)

This is the timetable of  8
8  x  1  =  8
8  x  2  =  16
8  x  3  =  24
8  x  4  =  32
8  x  5  =  40
8  x  6  =  48
8  x  7  =  56
8  x  8  =  64
8  x  9  =  72
8  x  10  =  80


In [18]:
for x in range(1,11):
    print('This is the timetable of ',x)
    i=1
    while i<=10:
        print(x,' x ', i,' = ',x*i)
        i=i+1

This is the timetable of  1
1  x  1  =  1
1  x  2  =  2
1  x  3  =  3
1  x  4  =  4
1  x  5  =  5
1  x  6  =  6
1  x  7  =  7
1  x  8  =  8
1  x  9  =  9
1  x  10  =  10
This is the timetable of  2
2  x  1  =  2
2  x  2  =  4
2  x  3  =  6
2  x  4  =  8
2  x  5  =  10
2  x  6  =  12
2  x  7  =  14
2  x  8  =  16
2  x  9  =  18
2  x  10  =  20
This is the timetable of  3
3  x  1  =  3
3  x  2  =  6
3  x  3  =  9
3  x  4  =  12
3  x  5  =  15
3  x  6  =  18
3  x  7  =  21
3  x  8  =  24
3  x  9  =  27
3  x  10  =  30
This is the timetable of  4
4  x  1  =  4
4  x  2  =  8
4  x  3  =  12
4  x  4  =  16
4  x  5  =  20
4  x  6  =  24
4  x  7  =  28
4  x  8  =  32
4  x  9  =  36
4  x  10  =  40
This is the timetable of  5
5  x  1  =  5
5  x  2  =  10
5  x  3  =  15
5  x  4  =  20
5  x  5  =  25
5  x  6  =  30
5  x  7  =  35
5  x  8  =  40
5  x  9  =  45
5  x  10  =  50
This is the timetable of  6
6  x  1  =  6
6  x  2  =  12
6  x  3  =  18
6  x  4  =  24
6  x  5  =  30
6  x  6  =  36
6  x  7

In [19]:
!pip install numpy

In [20]:
import numpy as np

In [21]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(A)

numpy.ndarray

In [23]:
A.ndim

2

In [24]:
A.shape

(3, 3)

In [25]:
A.size

9

In [28]:
A[-1,-1]

9

In [29]:
A[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [30]:
A[1,0:2]

array([4, 5])

In [31]:
X=np.array([[1,2,3],[4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
Y=np.array([[9,8,7],[6,5,4]])
Y

array([[9, 8, 7],
       [6, 5, 4]])

In [35]:
2*X-3*Y

array([[-25, -20, -15],
       [-10,  -5,   0]])

In [36]:
YT=Y.T
YT

array([[9, 6],
       [8, 5],
       [7, 4]])

In [37]:
X*Y #element times element

array([[ 9, 16, 21],
       [24, 25, 24]])

In [38]:
np.dot(X,YT) #matrix multiplication

array([[ 46,  28],
       [118,  73]])

In [39]:
np.dot(YT,X) #matrix multiplication

array([[33, 48, 63],
       [28, 41, 54],
       [23, 34, 45]])

In [40]:
!pip install pandas

In [41]:
import pandas as pd

In [42]:
csv_path="D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\TopSellingAlbums.csv"
df=pd.read_csv(csv_path)
df

Artist                            Album  Released   Length  \
0  Michael Jackson                         Thriller      1982  0:42:19   
1            AC/DC                    Back in Black      1980  0:42:11   
2       Pink Floyd        The Dark Side of the Moon      1973  0:42:49   
3  Whitney Houston                    The Bodyguard      1992  0:57:44   
4        Meat Loaf                  Bat Out of Hell      1977  0:46:33   
5           Eagles  Their Greatest Hits (1971-1975)      1976  0:43:08   
6         Bee Gees             Saturday Night Fever      1977  1:15:54   
7    Fleetwood Mac                          Rumours      1977  0:40:01   

                         Genre  Music Recording Sales (millions)  \
0               pop, rock, R&B                              46.0   
1                    hard rock                              26.1   
2             progressive rock                              24.2   
3               R&B, soul, pop                              27.4   
4  hard rock, progressive rock                              20.6   
5   rock, soft rock, folk rock                              32.2   
6                        disco                              20.6   
7                    soft rock                              27.9   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0  
3                        44  17-Nov-92          Y     8.5  
4                        43  21-Oct-77        NaN     8.0  
5                        42  17-Feb-76        NaN     7.5  
6                        40  15-Nov-77          Y     7.0  
7                        40  04-Feb-77        NaN     6.5

In [45]:
df.head(2)

Artist          Album  Released   Length           Genre  \
0  Michael Jackson       Thriller      1982  0:42:19  pop, rock, R&B   
1            AC/DC  Back in Black      1980  0:42:11       hard rock   

   Music Recording Sales (millions)  Claimed Sales (millions) Released.1  \
0                              46.0                        65  30-Nov-82   
1                              26.1                        50  25-Jul-80   

  Soundtrack  Rating  
0        NaN    10.0  
1        NaN     9.5

In [46]:
df2=df[['Artist','Album','Rating']]
df2

Artist                            Album  Rating
0  Michael Jackson                         Thriller    10.0
1            AC/DC                    Back in Black     9.5
2       Pink Floyd        The Dark Side of the Moon     9.0
3  Whitney Houston                    The Bodyguard     8.5
4        Meat Loaf                  Bat Out of Hell     8.0
5           Eagles  Their Greatest Hits (1971-1975)     7.5
6         Bee Gees             Saturday Night Fever     7.0
7    Fleetwood Mac                          Rumours     6.5

In [47]:
df.loc[1,'Album']

'Back in Black'

In [48]:
df.iloc[1,1]

'Back in Black'

In [49]:
df.iloc[0:2,1:3]

Album  Released
0       Thriller      1982
1  Back in Black      1980

In [50]:
df3=df[['Music Recording Sales (millions)']]
df3

Music Recording Sales (millions)
0                              46.0
1                              26.1
2                              24.2
3                              27.4
4                              20.6
5                              32.2
6                              20.6
7                              27.9

In [51]:
df3.describe()

Music Recording Sales (millions)
count                          8.000000
mean                          28.125000
std                            8.189322
min                           20.600000
25%                           23.300000
50%                           26.750000
75%                           28.975000
max                           46.000000

In [52]:
df.describe()

Released  Music Recording Sales (millions)  \
count     8.000000                          8.000000   
mean   1979.250000                         28.125000   
std       5.800246                          8.189322   
min    1973.000000                         20.600000   
25%    1976.750000                         23.300000   
50%    1977.000000                         26.750000   
75%    1980.500000                         28.975000   
max    1992.000000                         46.000000   

       Claimed Sales (millions)     Rating  
count                  8.000000   8.000000  
mean                  46.125000   8.250000  
std                    8.271077   1.224745  
min                   40.000000   6.500000  
25%                   41.500000   7.375000  
50%                   43.500000   8.250000  
75%                   46.250000   9.125000  
max                   65.000000  10.000000

In [55]:
#excel_path="D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\Customer Call List.xlsx"
#df=pd.read_excel(excel_path)
df=pd.read_excel(r"D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\Customer Call List.xlsx")
df

CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421   
1         1002       Abed        Nadir  123/643/9775   
2         1003     Walter       /White    7066950392   
3         1004     Dwight      Schrute  123-543-2345   
4         1005        Jon         Snow  876|678|3469   
5         1006        Ron      Swanson  304-762-2467   
6         1007       Jeff       Winger           NaN   
7         1008   Sherlock       Holmes  876|678|3469   
8         1009    Gandalf          NaN           N/a   
9         1010      Peter       Parker  123-545-5421   
10        1011    Samwise       Gamgee           NaN   
11        1012      Harry    ...Potter    7066950392   
12        1013        Don       Draper  123-543-2345   
13        1014     Leslie        Knope  876|678|3469   
14        1015       Toby  Flenderson_  304-762-2467   
15        1016        Ron      Weasley  123-545-5421   
16        1017   Michael         Scott  123/643/9775   
17        1018      Clark         Kent    7066950392   
18        1019      Creed       Braton           N/a   
19        1020     Anakin    Skywalker  876|678|3469   
20        1020     Anakin    Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No   
1                     93 West Main Street              No            Yes   
2                      298 Drugs Driveway               N            NaN   
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                        123 Dragons Road               Y             No   
5                        768 City Parkway             Yes            Yes   
6                       1209 South Street              No             No   
7                           98 Clue Drive               N             No   
8                        123 Middle Earth             Yes            NaN   
9              25th Main Street, New York             Yes             No   
10                  612 Shire Lane, Shire             Yes             No   
11                   2394 Hogwarts Avenue               Y            NaN   
12                       2039 Main Street             Yes              N   
13                       343 City Parkway             Yes             No   
14                          214 HR Avenue               N             No   
15                   2395 Hogwarts Avenue              No              N   
16         121 Paper Avenue, Pennsylvania             Yes             No   
17                        3498 Super Lane               Y            NaN   
18                                    N/a             N/a            Yes   
19            910 Tatooine Road, Tatooine             Yes              N   
20            910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column  
0                True  
1               False  
2                True  
3                True  
4                True  
5                True  
6               False  
7               False  
8               False  
9                True  
10               True  
11               True  
12              False  
13              False  
14              False  
15              False  
16              False  
17               True  
18               True  
19               True  
20               True

In [58]:
#drop duplicates
df=df.drop_duplicates()
df

CustomerID First_Name    Last_Name  Phone_Number  \
0         1001      Frodo      Baggins  123-545-5421   
1         1002       Abed        Nadir  123/643/9775   
2         1003     Walter       /White    7066950392   
3         1004     Dwight      Schrute  123-543-2345   
4         1005        Jon         Snow  876|678|3469   
5         1006        Ron      Swanson  304-762-2467   
6         1007       Jeff       Winger           NaN   
7         1008   Sherlock       Holmes  876|678|3469   
8         1009    Gandalf          NaN           N/a   
9         1010      Peter       Parker  123-545-5421   
10        1011    Samwise       Gamgee           NaN   
11        1012      Harry    ...Potter    7066950392   
12        1013        Don       Draper  123-543-2345   
13        1014     Leslie        Knope  876|678|3469   
14        1015       Toby  Flenderson_  304-762-2467   
15        1016        Ron      Weasley  123-545-5421   
16        1017   Michael         Scott  123/643/9775   
17        1018      Clark         Kent    7066950392   
18        1019      Creed       Braton           N/a   
19        1020     Anakin    Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No   
1                     93 West Main Street              No            Yes   
2                      298 Drugs Driveway               N            NaN   
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                        123 Dragons Road               Y             No   
5                        768 City Parkway             Yes            Yes   
6                       1209 South Street              No             No   
7                           98 Clue Drive               N             No   
8                        123 Middle Earth             Yes            NaN   
9              25th Main Street, New York             Yes             No   
10                  612 Shire Lane, Shire             Yes             No   
11                   2394 Hogwarts Avenue               Y            NaN   
12                       2039 Main Street             Yes              N   
13                       343 City Parkway             Yes             No   
14                          214 HR Avenue               N             No   
15                   2395 Hogwarts Avenue              No              N   
16         121 Paper Avenue, Pennsylvania             Yes             No   
17                        3498 Super Lane               Y            NaN   
18                                    N/a             N/a            Yes   
19            910 Tatooine Road, Tatooine             Yes              N   

    Not_Useful_Column  
0                True  
1               False  
2                True  
3                True  
4                True  
5                True  
6               False  
7               False  
8               False  
9                True  
10               True  
11               True  
12              False  
13              False  
14              False  
15              False  
16              False  
17               True  
18               True  
19               True

In [60]:
#drop columns
df=df.drop(columns='Not_Useful_Column')

In [63]:
df['Last_Name']=df['Last_Name'].str.strip('/\._-123')
df

CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421   
1         1002       Abed       Nadir  123/643/9775   
2         1003     Walter       White    7066950392   
3         1004     Dwight     Schrute  123-543-2345   
4         1005        Jon        Snow  876|678|3469   
5         1006        Ron     Swanson  304-762-2467   
6         1007       Jeff      Winger           NaN   
7         1008   Sherlock      Holmes  876|678|3469   
8         1009    Gandalf         NaN           N/a   
9         1010      Peter      Parker  123-545-5421   
10        1011    Samwise      Gamgee           NaN   
11        1012      Harry      Potter    7066950392   
12        1013        Don      Draper  123-543-2345   
13        1014     Leslie       Knope  876|678|3469   
14        1015       Toby  Flenderson  304-762-2467   
15        1016        Ron     Weasley  123-545-5421   
16        1017   Michael        Scott  123/643/9775   
17        1018      Clark        Kent    7066950392   
18        1019      Creed      Braton           N/a   
19        1020     Anakin   Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  
0                   123 Shire Lane, Shire             Yes             No  
1                     93 West Main Street              No            Yes  
2                      298 Drugs Driveway               N            NaN  
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y  
4                        123 Dragons Road               Y             No  
5                        768 City Parkway             Yes            Yes  
6                       1209 South Street              No             No  
7                           98 Clue Drive               N             No  
8                        123 Middle Earth             Yes            NaN  
9              25th Main Street, New York             Yes             No  
10                  612 Shire Lane, Shire             Yes             No  
11                   2394 Hogwarts Avenue               Y            NaN  
12                       2039 Main Street             Yes              N  
13                       343 City Parkway             Yes             No  
14                          214 HR Avenue               N             No  
15                   2395 Hogwarts Avenue              No              N  
16         121 Paper Avenue, Pennsylvania             Yes             No  
17                        3498 Super Lane               Y            NaN  
18                                    N/a             N/a            Yes  
19            910 Tatooine Road, Tatooine             Yes              N

In [65]:
df[['Street Adress','State','Zipcode']]=df['Address'].str.split(',',n=2,expand=True)
df

CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421   
1         1002       Abed       Nadir  123/643/9775   
2         1003     Walter       White    7066950392   
3         1004     Dwight     Schrute  123-543-2345   
4         1005        Jon        Snow  876|678|3469   
5         1006        Ron     Swanson  304-762-2467   
6         1007       Jeff      Winger           NaN   
7         1008   Sherlock      Holmes  876|678|3469   
8         1009    Gandalf         NaN           N/a   
9         1010      Peter      Parker  123-545-5421   
10        1011    Samwise      Gamgee           NaN   
11        1012      Harry      Potter    7066950392   
12        1013        Don      Draper  123-543-2345   
13        1014     Leslie       Knope  876|678|3469   
14        1015       Toby  Flenderson  304-762-2467   
15        1016        Ron     Weasley  123-545-5421   
16        1017   Michael        Scott  123/643/9775   
17        1018      Clark        Kent    7066950392   
18        1019      Creed      Braton           N/a   
19        1020     Anakin   Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  \
0                   123 Shire Lane, Shire             Yes             No   
1                     93 West Main Street              No            Yes   
2                      298 Drugs Driveway               N            NaN   
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y   
4                        123 Dragons Road               Y             No   
5                        768 City Parkway             Yes            Yes   
6                       1209 South Street              No             No   
7                           98 Clue Drive               N             No   
8                        123 Middle Earth             Yes            NaN   
9              25th Main Street, New York             Yes             No   
10                  612 Shire Lane, Shire             Yes             No   
11                   2394 Hogwarts Avenue               Y            NaN   
12                       2039 Main Street             Yes              N   
13                       343 City Parkway             Yes             No   
14                          214 HR Avenue               N             No   
15                   2395 Hogwarts Avenue              No              N   
16         121 Paper Avenue, Pennsylvania             Yes             No   
17                        3498 Super Lane               Y            NaN   
18                                    N/a             N/a            Yes   
19            910 Tatooine Road, Tatooine             Yes              N   

           Street Adress          State Zipcode  
0         123 Shire Lane          Shire    None  
1    93 West Main Street           None    None  
2     298 Drugs Driveway           None    None  
3       980 Paper Avenue   Pennsylvania   18503  
4       123 Dragons Road           None    None  
5       768 City Parkway           None    None  
6      1209 South Street           None    None  
7          98 Clue Drive           None    None  
8       123 Middle Earth           None    None  
9       25th Main Street       New York    None  
10        612 Shire Lane          Shire    None  
11  2394 Hogwarts Avenue           None    None  
12      2039 Main Street           None    None  
13      343 City Parkway           None    None  
14         214 HR Avenue           None    None  
15  2395 Hogwarts Avenue           None    None  
16      121 Paper Avenue   Pennsylvania    None  
17       3498 Super Lane           None    None  
18                   N/a           None    None  
19     910 Tatooine Road       Tatooine    None

In [66]:
df=df.drop(columns='Address')
df.head(2)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421             Yes   
1        1002       Abed     Nadir  123/643/9775              No   

  Do_Not_Contact        Street Adress   State Zipcode  
0             No       123 Shire Lane   Shire    None  
1            Yes  93 West Main Street    None    None

In [67]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')
df.head(3)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421               Y   
1        1002       Abed     Nadir  123/643/9775               N   
2        1003     Walter     White    7066950392               N   

  Do_Not_Contact        Street Adress   State Zipcode  
0             No       123 Shire Lane   Shire    None  
1            Yes  93 West Main Street    None    None  
2            NaN   298 Drugs Driveway    None    None

In [68]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')
df.head(3)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421               Y   
1        1002       Abed     Nadir  123/643/9775               N   
2        1003     Walter     White    7066950392               N   

  Do_Not_Contact        Street Adress   State Zipcode  
0              N       123 Shire Lane   Shire    None  
1              Y  93 West Main Street    None    None  
2            NaN   298 Drugs Driveway    None    None

In [69]:
df

CustomerID First_Name   Last_Name  Phone_Number Paying Customer  \
0         1001      Frodo     Baggins  123-545-5421               Y   
1         1002       Abed       Nadir  123/643/9775               N   
2         1003     Walter       White    7066950392               N   
3         1004     Dwight     Schrute  123-543-2345               Y   
4         1005        Jon        Snow  876|678|3469               Y   
5         1006        Ron     Swanson  304-762-2467               Y   
6         1007       Jeff      Winger           NaN               N   
7         1008   Sherlock      Holmes  876|678|3469               N   
8         1009    Gandalf         NaN           N/a               Y   
9         1010      Peter      Parker  123-545-5421               Y   
10        1011    Samwise      Gamgee           NaN               Y   
11        1012      Harry      Potter    7066950392               Y   
12        1013        Don      Draper  123-543-2345               Y   
13        1014     Leslie       Knope  876|678|3469               Y   
14        1015       Toby  Flenderson  304-762-2467               N   
15        1016        Ron     Weasley  123-545-5421               N   
16        1017   Michael        Scott  123/643/9775               Y   
17        1018      Clark        Kent    7066950392               Y   
18        1019      Creed      Braton           N/a             N/a   
19        1020     Anakin   Skywalker  876|678|3469               Y   

   Do_Not_Contact         Street Adress          State Zipcode  
0               N        123 Shire Lane          Shire    None  
1               Y   93 West Main Street           None    None  
2             NaN    298 Drugs Driveway           None    None  
3               Y      980 Paper Avenue   Pennsylvania   18503  
4               N      123 Dragons Road           None    None  
5               Y      768 City Parkway           None    None  
6               N     1209 South Street           None    None  
7               N         98 Clue Drive           None    None  
8             NaN      123 Middle Earth           None    None  
9               N      25th Main Street       New York    None  
10              N        612 Shire Lane          Shire    None  
11            NaN  2394 Hogwarts Avenue           None    None  
12              N      2039 Main Street           None    None  
13              N      343 City Parkway           None    None  
14              N         214 HR Avenue           None    None  
15              N  2395 Hogwarts Avenue           None    None  
16              N      121 Paper Avenue   Pennsylvania    None  
17            NaN       3498 Super Lane           None    None  
18              Y                   N/a           None    None  
19              N     910 Tatooine Road       Tatooine    None

In [71]:
#Drop all the N.A info
df['Phone_Number']=df['Phone_Number'].str.replace('N/a','')
df['Phone_Number']=df['Phone_Number'].str.replace('NaN','')
df

CustomerID First_Name   Last_Name  Phone_Number Paying Customer  \
0         1001      Frodo     Baggins  123-545-5421               Y   
1         1002       Abed       Nadir  123/643/9775               N   
2         1003     Walter       White           NaN               N   
3         1004     Dwight     Schrute  123-543-2345               Y   
4         1005        Jon        Snow  876|678|3469               Y   
5         1006        Ron     Swanson  304-762-2467               Y   
6         1007       Jeff      Winger           NaN               N   
7         1008   Sherlock      Holmes  876|678|3469               N   
8         1009    Gandalf         NaN                             Y   
9         1010      Peter      Parker  123-545-5421               Y   
10        1011    Samwise      Gamgee           NaN               Y   
11        1012      Harry      Potter           NaN               Y   
12        1013        Don      Draper  123-543-2345               Y   
13        1014     Leslie       Knope  876|678|3469               Y   
14        1015       Toby  Flenderson  304-762-2467               N   
15        1016        Ron     Weasley  123-545-5421               N   
16        1017   Michael        Scott  123/643/9775               Y   
17        1018      Clark        Kent           NaN               Y   
18        1019      Creed      Braton                           N/a   
19        1020     Anakin   Skywalker  876|678|3469               Y   

   Do_Not_Contact         Street Adress          State Zipcode  
0               N        123 Shire Lane          Shire    None  
1               Y   93 West Main Street           None    None  
2             NaN    298 Drugs Driveway           None    None  
3               Y      980 Paper Avenue   Pennsylvania   18503  
4               N      123 Dragons Road           None    None  
5               Y      768 City Parkway           None    None  
6               N     1209 South Street           None    None  
7               N         98 Clue Drive           None    None  
8             NaN      123 Middle Earth           None    None  
9               N      25th Main Street       New York    None  
10              N        612 Shire Lane          Shire    None  
11            NaN  2394 Hogwarts Avenue           None    None  
12              N      2039 Main Street           None    None  
13              N      343 City Parkway           None    None  
14              N         214 HR Avenue           None    None  
15              N  2395 Hogwarts Avenue           None    None  
16              N      121 Paper Avenue   Pennsylvania    None  
17            NaN       3498 Super Lane           None    None  
18              Y                   N/a           None    None  
19              N     910 Tatooine Road       Tatooine    None

In [73]:
df=df.fillna('')
df

CustomerID First_Name   Last_Name  Phone_Number Paying Customer  \
0         1001      Frodo     Baggins  123-545-5421               Y   
1         1002       Abed       Nadir  123/643/9775               N   
2         1003     Walter       White                             N   
3         1004     Dwight     Schrute  123-543-2345               Y   
4         1005        Jon        Snow  876|678|3469               Y   
5         1006        Ron     Swanson  304-762-2467               Y   
6         1007       Jeff      Winger                             N   
7         1008   Sherlock      Holmes  876|678|3469               N   
8         1009    Gandalf                                         Y   
9         1010      Peter      Parker  123-545-5421               Y   
10        1011    Samwise      Gamgee                             Y   
11        1012      Harry      Potter                             Y   
12        1013        Don      Draper  123-543-2345               Y   
13        1014     Leslie       Knope  876|678|3469               Y   
14        1015       Toby  Flenderson  304-762-2467               N   
15        1016        Ron     Weasley  123-545-5421               N   
16        1017   Michael        Scott  123/643/9775               Y   
17        1018      Clark        Kent                             Y   
18        1019      Creed      Braton                           N/a   
19        1020     Anakin   Skywalker  876|678|3469               Y   

   Do_Not_Contact         Street Adress          State Zipcode  
0               N        123 Shire Lane          Shire          
1               Y   93 West Main Street                         
2                    298 Drugs Driveway                         
3               Y      980 Paper Avenue   Pennsylvania   18503  
4               N      123 Dragons Road                         
5               Y      768 City Parkway                         
6               N     1209 South Street                         
7               N         98 Clue Drive                         
8                      123 Middle Earth                         
9               N      25th Main Street       New York          
10              N        612 Shire Lane          Shire          
11                 2394 Hogwarts Avenue                         
12              N      2039 Main Street                         
13              N      343 City Parkway                         
14              N         214 HR Avenue                         
15              N  2395 Hogwarts Avenue                         
16              N      121 Paper Avenue   Pennsylvania          
17                      3498 Super Lane                         
18              Y                   N/a                         
19              N     910 Tatooine Road       Tatooine

In [76]:
#drop customers with no phone numbers
for x in df.index:
    if df.loc[x,"Phone_Number"] =='':
        df.drop(x,inplace=True)
df

CustomerID First_Name   Last_Name  Phone_Number Paying Customer  \
0         1001      Frodo     Baggins  123-545-5421               Y   
1         1002       Abed       Nadir  123/643/9775               N   
3         1004     Dwight     Schrute  123-543-2345               Y   
4         1005        Jon        Snow  876|678|3469               Y   
5         1006        Ron     Swanson  304-762-2467               Y   
7         1008   Sherlock      Holmes  876|678|3469               N   
9         1010      Peter      Parker  123-545-5421               Y   
12        1013        Don      Draper  123-543-2345               Y   
13        1014     Leslie       Knope  876|678|3469               Y   
14        1015       Toby  Flenderson  304-762-2467               N   
15        1016        Ron     Weasley  123-545-5421               N   
16        1017   Michael        Scott  123/643/9775               Y   
19        1020     Anakin   Skywalker  876|678|3469               Y   

   Do_Not_Contact         Street Adress          State Zipcode  
0               N        123 Shire Lane          Shire          
1               Y   93 West Main Street                         
3               Y      980 Paper Avenue   Pennsylvania   18503  
4               N      123 Dragons Road                         
5               Y      768 City Parkway                         
7               N         98 Clue Drive                         
9               N      25th Main Street       New York          
12              N      2039 Main Street                         
13              N      343 City Parkway                         
14              N         214 HR Avenue                         
15              N  2395 Hogwarts Avenue                         
16              N      121 Paper Avenue   Pennsylvania          
19              N     910 Tatooine Road       Tatooine