In [32]:
##String

In [2]:
print("Hello World")

Hello World


In [7]:
a="Hello World"
a

'Hello World'

In [5]:
type(a)

str

In [8]:
len(a)

11

In [17]:
print(a[::2])

HloWrd


In [18]:
b = a+" Miss Sunny"
b

'Hello World Miss Sunny'

In [22]:
a.replace("World", "Ocean")

'Hello Ocean'

In [25]:
a.find("or")

7

In [30]:
print("Hello Fin 2 \t Hope that it is nice to me!")

Hello Fin 2 	 Hope that it is nice to me!


In [34]:
2+4*(5-6)*2.2

-6.800000000000001

In [35]:
x=4*7
y=5/4
z=x+y
z

29.25

In [36]:
print('z is equal to ',z)

z is equal to  29.25


In [41]:
165//60

2

In [42]:
L=['Hello World', 2024, 8.30,"Oct"]
L

['Hello World', 2024, 8.3, 'Oct']

In [44]:
T=('Hello World', 2024, 8.30,"Oct")
T

('Hello World', 2024, 8.3, 'Oct')

In [46]:
L.extend(["Autumn", 21])
L

['Hello World', 2024, 8.3, 'Oct', 'Autumn', 21, 'Autumn', 21]

In [51]:
L.remove("Autumn")
L

['Hello World', 2024, 8.3, 'Oct', 'Autumn', 21]

In [52]:
L.append(["Autumn", 21])

In [53]:
L

['Hello World', 2024, 8.3, 'Oct', 'Autumn', 21, ['Autumn', 21]]

In [56]:
S={"chocolate","vanilla","chocolate","matcha"}
S

{'chocolate', 'matcha', 'vanilla'}

In [58]:
L1=["chocolate","vanilla","chocolate","matcha"]
L1

['chocolate', 'vanilla', 'chocolate', 'matcha']

In [59]:
5==6

False

5!=6

In [60]:
5!=6

True

In [64]:
10!=20 or 5==6

True

In [65]:
a="Vanilla"
b="Chocolate"
c="Vanilla Ice cream"

In [68]:
b not in c

True

In [70]:
"6" in c

False

In [77]:
age=24
if age <18:
    print("You can have a candy")
elif age<20:
    print("You can have an ice cream")
elif age<25:
    print("You can have an sweet")
else:
    print("Sorry. Too old")


You can have an sweet


In [79]:
2001%4

1

In [2]:
for i in range(-5,6):
    print(i)

-5
-4
-3
-2
-1
0
1
2
3
4
5


In [6]:
Genres=["rock","R&B",'Soundtrack','R&B','soul','pop','rock']
n=len(Genres)
for i in range(n):
    print(Genres[i])       

rock
R&B
Soundtrack
R&B
soul
pop
rock


In [7]:
PlayListRatings = [10, 9.5, 10, 8, 7.5, 5, 10, 10]
i=0
ratings=PlayListRatings[i]
while ratings>=6:
    print(PlayListRatings[i])
    i=i+1
    ratings=PlayListRatings[i]

10
9.5
10
8
7.5


In [11]:
x=9
print("This is the timetable of ",x)
for i in range(1,11):
    print(x," x ",i,' = ',x*i)
    

This is the timetable of  9
9  x  1  =  9
9  x  2  =  18
9  x  3  =  27
9  x  4  =  36
9  x  5  =  45
9  x  6  =  54
9  x  7  =  63
9  x  8  =  72
9  x  9  =  81
9  x  10  =  90


In [16]:
for x in range(1,3):
    print("This is the timetable of ",x)
    i=1
    while i<=10:
        print(x," x ",i,' = ',x*i)
        i=i+1

This is the timetable of  1
1  x  1  =  1
1  x  2  =  2
1  x  3  =  3
1  x  4  =  4
1  x  5  =  5
1  x  6  =  6
1  x  7  =  7
1  x  8  =  8
1  x  9  =  9
1  x  10  =  10
This is the timetable of  2
2  x  1  =  2
2  x  2  =  4
2  x  3  =  6
2  x  4  =  8
2  x  5  =  10
2  x  6  =  12
2  x  7  =  14
2  x  8  =  16
2  x  9  =  18
2  x  10  =  20


In [17]:
!pip install numpy

In [18]:
import numpy as np

In [25]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
type(A)

numpy.ndarray

In [21]:
A.ndim

2

In [24]:
A.shape

(2, 3)

In [30]:
A[0,0:2]

array([1, 2])

In [31]:
X=np.array([[1,2,3],[4,5,6]])
X

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
Y=np.array([[2,3,4],[6,7,8]])
Y

array([[2, 3, 4],
       [6, 7, 8]])

In [37]:
2*Y+3*X

array([[ 7, 12, 17],
       [24, 29, 34]])

In [39]:
YT=Y.T
YT

array([[2, 6],
       [3, 7],
       [4, 8]])

In [40]:
X*Y #element x element

array([[ 2,  6, 12],
       [24, 35, 48]])

In [41]:
np.dot(X,YT)

array([[ 20,  44],
       [ 47, 107]])

In [42]:
np.dot(YT,X)

array([[26, 34, 42],
       [31, 41, 51],
       [36, 48, 60]])

In [44]:
np.dot(YT,X)

array([[26, 34, 42],
       [31, 41, 51],
       [36, 48, 60]])

In [45]:
!pip install pandas

In [46]:
import pandas as pd

In [48]:
csv_path="D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\TopSellingAlbums.csv"
df=pd.read_csv(csv_path)


In [55]:
df.head(3)

Artist                      Album  Released   Length  \
0  Michael Jackson                   Thriller      1982  0:42:19   
1            AC/DC              Back in Black      1980  0:42:11   
2       Pink Floyd  The Dark Side of the Moon      1973  0:42:49   

              Genre  Music Recording Sales (millions)  \
0    pop, rock, R&B                              46.0   
1         hard rock                              26.1   
2  progressive rock                              24.2   

   Claimed Sales (millions) Released.1 Soundtrack  Rating  
0                        65  30-Nov-82        NaN    10.0  
1                        50  25-Jul-80        NaN     9.5  
2                        45  01-Mar-73        NaN     9.0

In [52]:
df2=df[['Artist','Album','Rating']]
df2

Artist                            Album  Rating
0  Michael Jackson                         Thriller    10.0
1            AC/DC                    Back in Black     9.5
2       Pink Floyd        The Dark Side of the Moon     9.0
3  Whitney Houston                    The Bodyguard     8.5
4        Meat Loaf                  Bat Out of Hell     8.0
5           Eagles  Their Greatest Hits (1971-1975)     7.5
6         Bee Gees             Saturday Night Fever     7.0
7    Fleetwood Mac                          Rumours     6.5

In [53]:
df.loc[2,"Album"]

'The Dark Side of the Moon'

In [57]:
df.iloc[0:2,2:4]

Released   Length
0      1982  0:42:19
1      1980  0:42:11

In [58]:
df3=df[["Music Recording Sales (millions)"]]
df3

Music Recording Sales (millions)
0                              46.0
1                              26.1
2                              24.2
3                              27.4
4                              20.6
5                              32.2
6                              20.6
7                              27.9

In [61]:
df.describe()

Released  Music Recording Sales (millions)  \
count     8.000000                          8.000000   
mean   1979.250000                         28.125000   
std       5.800246                          8.189322   
min    1973.000000                         20.600000   
25%    1976.750000                         23.300000   
50%    1977.000000                         26.750000   
75%    1980.500000                         28.975000   
max    1992.000000                         46.000000   

       Claimed Sales (millions)     Rating  
count                  8.000000   8.000000  
mean                  46.125000   8.250000  
std                    8.271077   1.224745  
min                   40.000000   6.500000  
25%                   41.500000   7.375000  
50%                   43.500000   8.250000  
75%                   46.250000   9.125000  
max                   65.000000  10.000000

In [65]:
#excel_path="D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\Customer Call List.xlsx"
#df=pd.read_excel(excel_path)
df=pd.read_excel(r"D:\Anh Nguyen\Anh's documents\Teaching Materials\Fin2\Codes\Working with Python\Customer Call List.xlsx")

In [67]:
#drop duplicates
df=df.drop_duplicates()

In [69]:
#drop columns
df=df.drop(columns="Not_Useful_Column")

In [71]:
df['Last_Name']=df['Last_Name'].str.strip('/\.-_123')
df

CustomerID First_Name   Last_Name  Phone_Number  \
0         1001      Frodo     Baggins  123-545-5421   
1         1002       Abed       Nadir  123/643/9775   
2         1003     Walter       White    7066950392   
3         1004     Dwight     Schrute  123-543-2345   
4         1005        Jon        Snow  876|678|3469   
5         1006        Ron     Swanson  304-762-2467   
6         1007       Jeff      Winger           NaN   
7         1008   Sherlock      Holmes  876|678|3469   
8         1009    Gandalf         NaN           N/a   
9         1010      Peter      Parker  123-545-5421   
10        1011    Samwise      Gamgee           NaN   
11        1012      Harry      Potter    7066950392   
12        1013        Don      Draper  123-543-2345   
13        1014     Leslie       Knope  876|678|3469   
14        1015       Toby  Flenderson  304-762-2467   
15        1016        Ron     Weasley  123-545-5421   
16        1017   Michael        Scott  123/643/9775   
17        1018      Clark        Kent    7066950392   
18        1019      Creed      Braton           N/a   
19        1020     Anakin   Skywalker  876|678|3469   

                                  Address Paying Customer Do_Not_Contact  
0                   123 Shire Lane, Shire             Yes             No  
1                     93 West Main Street              No            Yes  
2                      298 Drugs Driveway               N            NaN  
3   980 Paper Avenue, Pennsylvania, 18503             Yes              Y  
4                        123 Dragons Road               Y             No  
5                        768 City Parkway             Yes            Yes  
6                       1209 South Street              No             No  
7                           98 Clue Drive               N             No  
8                        123 Middle Earth             Yes            NaN  
9              25th Main Street, New York             Yes             No  
10                  612 Shire Lane, Shire             Yes             No  
11                   2394 Hogwarts Avenue               Y            NaN  
12                       2039 Main Street             Yes              N  
13                       343 City Parkway             Yes             No  
14                          214 HR Avenue               N             No  
15                   2395 Hogwarts Avenue              No              N  
16         121 Paper Avenue, Pennsylvania             Yes             No  
17                        3498 Super Lane               Y            NaN  
18                                    N/a             N/a            Yes  
19            910 Tatooine Road, Tatooine             Yes              N

In [75]:
df[['Street Adress','State','Zipcode']]=df['Address'].str.split(',',n=2,expand=True)
df.head(2)

CustomerID First_Name Last_Name  Phone_Number                Address  \
0        1001      Frodo   Baggins  123-545-5421  123 Shire Lane, Shire   
1        1002       Abed     Nadir  123/643/9775    93 West Main Street   

  Paying Customer Do_Not_Contact        Street Adress   State Zipcode  
0             Yes             No       123 Shire Lane   Shire    None  
1              No            Yes  93 West Main Street    None    None

In [76]:
df=df.drop(columns="Address")
df.head(2)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421             Yes   
1        1002       Abed     Nadir  123/643/9775              No   

  Do_Not_Contact        Street Adress   State Zipcode  
0             No       123 Shire Lane   Shire    None  
1            Yes  93 West Main Street    None    None

In [78]:
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('Yes','Y')
df['Do_Not_Contact']=df['Do_Not_Contact'].str.replace('No','N')
df.head(3)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421             Yes   
1        1002       Abed     Nadir  123/643/9775              No   
2        1003     Walter     White    7066950392               N   

  Do_Not_Contact        Street Adress   State Zipcode  
0              N       123 Shire Lane   Shire    None  
1              Y  93 West Main Street    None    None  
2            NaN   298 Drugs Driveway    None    None

In [79]:
df['Paying Customer']=df['Paying Customer'].str.replace('Yes','Y')
df['Paying Customer']=df['Paying Customer'].str.replace('No','N')
df.head(3)

CustomerID First_Name Last_Name  Phone_Number Paying Customer  \
0        1001      Frodo   Baggins  123-545-5421               Y   
1        1002       Abed     Nadir  123/643/9775               N   
2        1003     Walter     White    7066950392               N   

  Do_Not_Contact        Street Adress   State Zipcode  
0              N       123 Shire Lane   Shire    None  
1              Y  93 West Main Street    None    None  
2            NaN   298 Drugs Driveway    None    None